# Generated by Django 3.2.8 on 2021-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdisease',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
